import { pick } from 'lodash';

export type CountriesType = keyof typeof countries;
const countries: { [key: string]: string } = {
	AF: 'afghanistan',
	AX: 'alandIslands',
	AL: 'albania',
	DZ: 'algeria',
	AS: 'americanSamoa',
	AD: 'andorra',
	AO: 'angola',
	AI: 'anguilla',
	AG: 'antiguaAndBarbuda',
	AR: 'argentina',
	AM: 'armenia',
	AW: 'aruba',
	AU: 'australia',
	AT: 'austria',
	AZ: 'azerbaijan',
	BS: 'bahamas',
	BH: 'bahrain',
	BD: 'bangladesh',
	BB: 'barbados',
	BY: 'belarus',
	BE: 'belgium',
	BZ: 'belize',
	BJ: 'benin',
	BM: 'bermuda',
	BT: 'bhutan',
	BO: 'bolivia',
	BA: 'bosniaAndHerzegovina',
	BW: 'botswana',
	BR: 'brazil',
	IO: 'britishIndianOceanTerritory',
	BN: 'brunei',
	BG: 'bulgaria',
	BF: 'burkinaFaso',
	BI: 'burundi',
	KH: 'cambodia',
	CM: 'cameroon',
	CA: 'canada',
	CV: 'capeVerde',
	KY: 'caymanIslands',
	CF: 'centralAfricanRepublic',
	TD: 'chad',
	CL: 'chile',
	CN: 'china',
	CX: 'christmas Island',
	CC: 'cocosIsland',
	CO: 'colombia',
	KM: 'comoros',
	CK: 'cookIslands',
	CR: 'costaRica',
	HR: 'croatia',
	CU: 'cuba',
	CY: 'cyprus',
	CZ: 'czechRepublic',
	CD: 'democraticRepublicOfCongo',
	DK: 'denmark',
	DJ: 'djibouti',
	DM: 'dominica',
	DO: 'dominicanRepublic',
	EC: 'ecuador',
	TL: 'eastTimor',
	EU: 'europeanUnion',
	EG: 'egypt',
	SV: 'elSalvador',
	GQ: 'equatorialGuinea',
	ER: 'eritrea',
	EE: 'estonia',
	ET: 'ethiopia',
	FK: 'falklandIslands',
	FO: 'faroeIslands',
	FJ: 'fiji',
	FI: 'finland',
	FR: 'france',
	PF: 'frenchPolynesia',
	GA: 'gabon',
	GM: 'gambia',
	GE: 'georgia',
	DE: 'germany',
	GH: 'ghana',
	GI: 'gibraltar',
	GR: 'greece',
	GL: 'greenland',
	GD: 'grenada',
	GU: 'guam',
	GT: 'guatemala',
	GG: 'guernsey',
	GW: 'guineaBissau',
	GN: 'guinea',
	GY: 'guyana',
	HT: 'haiti',
	HN: 'honduras',
	HK: 'hongKong',
	HU: 'hungary',
	IS: 'iceland',
	IN: 'india',
	ID: 'indonesia',
	IR: 'iran',
	IQ: 'iraq',
	IE: 'ireland',
	IM: 'isleOfMan',
	IL: 'israel',
	IT: 'italy',
	CI: 'ivoryCoast',
	JM: 'jamaica',
	JP: 'japan',
	JE: 'jersey',
	JO: 'jordan',
	KZ: 'kazakhstan',
	KE: 'kenya',
	KI: 'kiribati',
	KW: 'kuwait',
	KG: 'kyrgyzstan',
	LA: 'laos',
	LV: 'latvia',
	LB: 'lebanon',
	LS: 'lesotho',
	LR: 'liberia',
	LY: 'libya',
	LI: 'liechtenstein',
	LT: 'lithuania',
	LU: 'luxembourg',
	MO: 'macao',
	MG: 'madagascar',
	MW: 'malawi',
	MY: 'malaysia',
	MV: 'maldives',
	ML: 'mali',
	MT: 'malta',
	MH: 'marshallIslands',
	MQ: 'martinique',
	MR: 'mauritania',
	MU: 'mauritius',
	MX: 'mexico',
	FM: 'micronesia',
	MD: 'moldova',
	MC: 'monaco',
	MN: 'mongolia',
	ME: 'montenegro',
	MS: 'montserrat',
	MA: 'morocco',
	MZ: 'mozambique',
	MM: 'myanmar',
	NA: 'namibia',
	NR: 'nauru',
	NP: 'nepal',
	NL: 'netherlands',
	NZ: 'newZealand',
	NI: 'nicaragua',
	NE: 'niger',
	NG: 'nigeria',
	NU: 'niue',
	NF: 'norfolkIsland',
	MP: 'northernMarianaIslands',
	NO: 'norway',
	OM: 'oman',
	PK: 'pakistan',
	PW: 'palau',
	PS: 'palestine',
	PA: 'panama',
	PG: 'papuaNovaGuinea',
	PY: 'paraguay',
	PE: 'peru',
	PH: 'philippines',
	PN: 'pitcairnIslands',
	PL: 'poland',
	PT: 'portugal',
	PR: 'puertoRico',
	QA: 'qatar',
	MK: 'republicOfMacedonia',
	CG: 'republicOfTheCongo',
	RO: 'romania',
	RU: 'russia',
	RW: 'rwanda',
	WS: 'samoa',
	SM: 'sanMarino',
	ST: 'saoTomeAndPrincipe',
	SA: 'saudiArabia',
	SN: 'senegal',
	RS: 'serbia',
	SC: 'seychelles',
	SL: 'sierraLeone',
	SG: 'singapore',
	SK: 'slovakia',
	SI: 'slovenia',
	SB: 'solomonIslands',
	SO: 'somalia',
	ZA: 'southAfrica',
	KR: 'southKorea',
	ES: 'spain',
	LK: 'sriLanka',
	BL: 'stBarts',
	LC: 'stLucia',
	VC: 'stVincentAndTheGrenadines',
	SD: 'sudan',
	SR: 'suriname',
	SZ: 'swaziland',
	SE: 'sweden',
	CH: 'switzerland',
	SY: 'syria',
	TW: 'taiwan',
	TJ: 'tajikistan',
	TZ: 'tanzania',
	TH: 'thailand',
	TG: 'togo',
	TK: 'tokelau',
	TO: 'tonga',
	TT: 'trinidadAndTobago',
	TN: 'tunisia',
	TR: 'turkey',
	TM: 'turkmenistan',
	TC: 'turksAndCaicos',
	TV: 'tuvalu',
	UG: 'uganda',
	UA: 'ukraine',
	AE: 'unitedArabEmirates',
	GB: 'unitedKingdom',
	US: 'unitedStates',
	UY: 'uruguay',
	UZ: 'uzbekistan',
	VU: 'vanuatu',
	VA: 'vaticanCity',
	VE: 'venezuela',
	VN: 'vietnam',
	VG: 'virginIslands',
	YE: 'yemen',
	ZM: 'zambia',
	ZW: 'zimbabwe'
};

const euroCountries = pick(
	countries,
	'BE',
	'DE',
	'IE',
	'ES',
	'FR',
	'IT',
	'LU',
	'NL',
	'AT',
	'PT',
	'FI',
	'GR',
	'SK',
	'SI',
	'CY',
	'MT',
	'EE',
	'LV',
	'LT'
);

export { countries, euroCountries };
